### ISSUE TITLE
Add tabs element

### ISSUE THREAD

**Issue by rosclaritha** [phisoft/kertasdms-web#24]
To add tabs elements in between `NEVER LOSE ANOTHER DOCUMENT` and `IMPROVED WAY OF WORKING`

![image](https://user-images.githubusercontent.com/30463117/161910911-63e6d9e3-1553-4101-b5ed-ff84a9bc2efa.png)

Tab must have the following:
- [x] Tab label
- [x] Tab content
- [x] Tab must be functional. The tab content changes according to selected tab. (JavaScript)

Tab example:

![image](https://user-images.githubusercontent.com/30463117/161911414-1b454f38-700b-4d14-bc39-fa2c74435b50.png)
![image](https://user-images.githubusercontent.com/30463117/161911459-a6cf3931-dfde-4841-823b-e9fb74c01b7b.png)

**Comment by russel0907** [comment]
Add functional tabs element;

![Screenshot (237)](https://user-images.githubusercontent.com/94702093/162131384-52d80d13-dda9-4d37-8d06-19ffe40838ca.png)
