### ISSUE TITLE
Edit description layout

### ISSUE THREAD

**Issue by rosclaritha** [phisoft/kertasdms-web#25]
- [x] make image transparent
- [x] make description `left align`
- [x] make description size bigger

(1) Make description bigger
<img width="1137" alt="Screenshot 2022-04-07 at 1 54 37 PM" src="https://user-images.githubusercontent.com/30463117/162130033-59239ed9-1cea-4ffb-ac87-7bcd8d5351f3.png">
hare&utm_medium=link2&utm_source=sharebutton

(2) Make image background transparent
![image](https://user-images.githubusercontent.com/30463117/162130169-dfb68199-02c4-4d8a-a2d8-4da7ee2b1183.png)

**Comment by russel0907** [comment]
Edit description layout;

make image transparent
make description left align
make description size bigger

![Screenshot (251)](https://user-images.githubusercontent.com/94702093/162982816-2c5b280a-5112-4802-8514-36de270fa900.png)
