### ISSUE TITLE
Update web font

### ISSUE THREAD

**Issue by rosclaritha** [phisoft/kertasdms-web#26]
Find suitable font style and change the web font.

**Comment by russel0907** [comment]
Update web font;

![Screenshot 2022-04-13 at 23-14-39 KertasDMS - Document Tracking with QRCode](https://user-images.githubusercontent.com/94702093/163213215-997ae141-e4b6-4a75-9a8c-b71249d94804.png)

![code](https://user-images.githubusercontent.com/94702093/163213239-ee06dd13-73a8-4a81-a0aa-839c9c389a20.png)
