### ISSUE TITLE
Update tabs content

### ISSUE THREAD

**Issue by rosclaritha** [phisoft/kertasdms-web#28]
![image](https://user-images.githubusercontent.com/30463117/163300878-d4fdc3e3-1e5c-4772-9405-feb25a3f106f.png)

Task

- [x] Update title to -> What industries can KertasDMS help?
- [x] Find suitable photo to match with industry

`Education`
KertasDMS can be adopted by school districts, universities, and other Education Institutions. You can track filing process for the staff, student, and faculty members alike.
- Student files
- Teacher evaluations
- Administration documents
- Lab form
- Student application

`Government`
The local, state, and federal government agencies can adopt KertasDMS to track their documentation progress and location. KertasDMS is compliments the agencies existing workflow and can be quickly adopted without hassle. 
- Classified documents
- Case files
- Service information
- Public documents

`Business`
Businesses of all types can rely on KertasDMS to meet their document tracking needs. Business of various aspects can easily adopt KertasDMS into their daily operation.
- Leasing files
- Reports & files
- Financing documents
- Customer files

`Contractors`
Contractor companies can use KertasDMS to manage the large volume of equipment critical to their day-to-day operations.
- Jobsite documentation
- Equipment documentation
- Invoices 
- Warranty information

**Comment by russel0907** [comment]
Update tabs content;

Default;
![127 0 0 1_5500_index html(Nest Hub Max)](https://user-images.githubusercontent.com/94702093/163325538-b1779dd8-90cd-437c-a204-6d04b23baa2e.png)

Ipad view;
![127 0 0 1_5500_index html(iPad Air)](https://user-images.githubusercontent.com/94702093/163325520-69ceb5d2-495e-45ed-a2e8-28a9b62d316b.png)

Mobile view;
![127 0 0 1_5500_index html(iPhone 12 Pro)](https://user-images.githubusercontent.com/94702093/163325495-1ca12118-48a3-47d4-b21c-bf26ac1dc6c9.png)
