### ISSUE TITLE
Make image transparent

### ISSUE THREAD

**Issue by rosclaritha** [phisoft/kertasdms-web#31]
Edit description layout for the following similar to issue https://github.com/phisoft/kertasdms-web/issues/25

![image](https://user-images.githubusercontent.com/30463117/163300636-2c12b365-6309-4c40-ab88-b2d156cc00e1.png)
 
![image](https://user-images.githubusercontent.com/30463117/163300665-34a55f3b-885a-4a30-8625-99a89d4dd3c3.png)

**Comment by russel0907** [comment]
Make image transparent;

![Screenshot 2022-04-16 at 00-12-00 KertasDMS - Document Tracking with QRCode](https://user-images.githubusercontent.com/94702093/163652821-fcd6b3d2-b477-421a-95d5-49cc6088a0bf.png)

![Screenshot 2022-04-16 at 00-12-12 KertasDMS - Document Tracking with QRCode](https://user-images.githubusercontent.com/94702093/163652826-4de16600-9a72-4ecd-86d7-94f357a1a938.png)
