### ISSUE TITLE
Adjust padding

### ISSUE THREAD

**Issue by rosclaritha** [phisoft/kertasdms-web#37]
On tablet/ipad view:

`Flow`

- [x] add padding above Scan & Upload
- [x] adjust for mobile view

![Screen Shot 2022-06-10 at 14 27 15](https://user-images.githubusercontent.com/30463117/173004211-aac7219e-7837-4acf-b9bd-dff01a5398e2.png)

`Industries`

- [x] make the image and description same padding with tab 
- [x] adjust for mobile view
![image](https://user-images.githubusercontent.com/30463117/173004317-2a02d6b3-ec1c-4e3b-94e7-0c7d5425696b.png)

**Comment by russel0907** [comment]
**1. Adjust content's padding inside tab section;
2. Fix padding responsiveness;**

## Ipad View
![Screenshot 2022-06-11 at 10-28-57 KertasDMS - Document Tracking with QRCode](https://user-images.githubusercontent.com/94702093/173169306-84901c62-9567-45be-b4c3-1ceaefe949a4.png)


## Mobile View
![Screenshot 2022-06-11 at 10-29-12 KertasDMS - Document Tracking with QRCode](https://user-images.githubusercontent.com/94702093/173169310-335c72c6-6c1e-459e-a3de-ce7a62ee6532.png)
